USE [master]
GO

/****** Object:  Database [MIMIC3]    Script Date: 4/14/2019 4:51:01 PM ******/
DROP DATABASE [MIMIC3]
GO

/****** Object:  Database [MIMIC3]    Script Date: 4/14/2019 4:51:01 PM ******/
CREATE DATABASE [MIMIC3]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MIMIC3', FILENAME = N'C:\Users\saiem\Documents\mimic-code-data-1.4.1\MIMIC3.mdf' , SIZE = 22528000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 512000KB )
 LOG ON 
( NAME = N'MIMIC3_log', FILENAME = N'C:\Users\saiem\Documents\mimic-code-data-1.4.1\MIMIC3_log.ldf' , SIZE = 23595200KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [MIMIC3] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MIMIC3].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MIMIC3] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MIMIC3] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MIMIC3] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MIMIC3] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MIMIC3] SET ARITHABORT OFF 
GO

ALTER DATABASE [MIMIC3] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MIMIC3] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MIMIC3] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MIMIC3] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MIMIC3] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MIMIC3] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MIMIC3] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MIMIC3] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MIMIC3] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MIMIC3] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MIMIC3] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MIMIC3] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MIMIC3] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MIMIC3] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MIMIC3] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MIMIC3] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MIMIC3] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MIMIC3] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MIMIC3] SET  MULTI_USER 
GO

ALTER DATABASE [MIMIC3] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MIMIC3] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MIMIC3] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MIMIC3] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MIMIC3] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MIMIC3] SET QUERY_STORE = OFF
GO

ALTER DATABASE [MIMIC3] SET  READ_WRITE 
GO


USE [MIMIC3]
GO

/****** Object:  Table [dbo].[ADMISSIONS]    Script Date: 4/14/2019 4:52:18 PM ******/
DROP TABLE [dbo].[ADMISSIONS]
GO

/****** Object:  Table [dbo].[ADMISSIONS]    Script Date: 4/14/2019 4:52:18 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ADMISSIONS](
	[ROW_ID] [int] NOT NULL,
	[SUBJECT_ID] [int] NOT NULL,
	[HADM_ID] [int] NOT NULL,
	[ADMITTIME] [datetime] NOT NULL,
	[DISCHTIME] [datetime] NOT NULL,
	[DEATHTIME] [datetime] NULL,
	[ADMISSION_TYPE] [varchar](50) NOT NULL,
	[ADMISSION_LOCATION] [varchar](50) NOT NULL,
	[DISCHARGE_LOCATION] [varchar](50) NOT NULL,
	[INSURANCE] [varchar](255) NOT NULL,
	[LANGUAGE] [varchar](10) NULL,
	[RELIGION] [varchar](50) NULL,
	[MARITAL_STATUS] [varchar](50) NULL,
	[ETHNICITY] [varchar](200) NOT NULL,
	[EDREGTIME] [datetime] NULL,
	[EDOUTTIME] [datetime] NULL,
	[DIAGNOSIS] [varchar](300) NULL,
	[HOSPITAL_EXPIRE_FLAG] [tinyint] NOT NULL,
	[HAS_CHARTEVENTS_DATA] [tinyint] NOT NULL,
 CONSTRAINT [PK_ADMISSIONS] PRIMARY KEY CLUSTERED 
(
	[HADM_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


DROP TABLE [dbo].[CALLOUT]
GO

/****** Object:  Table [dbo].[CALLOUT]    Script Date: 4/14/2019 4:53:52 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CALLOUT](
	[ROW_ID] [int] NOT NULL,
	[SUBJECT_ID] [int] NOT NULL,
	[HADM_ID] [int] NOT NULL,
	[SUBMIT_WARDID] [tinyint] NULL,
	[SUBMIT_CAREUNIT] [varchar](15) NULL,
	[CURR_WARDID] [tinyint] NULL,
	[CURR_CAREUNIT] [varchar](15) NULL,
	[CALLOUT_WARDID] [tinyint] NOT NULL,
	[CALLOUT_SERVICE] [varchar](255) NOT NULL,
	[REQUEST_TELE] [tinyint] NOT NULL,
	[REQUEST_RESP] [tinyint] NOT NULL,
	[REQUEST_CDIFF] [tinyint] NOT NULL,
	[REQUEST_MRSA] [tinyint] NOT NULL,
	[REQUEST_VRE] [tinyint] NOT NULL,
	[CALLOUT_STATUS] [varchar](255) NOT NULL,
	[CALLOUT_OUTCOME] [varchar](255) NOT NULL,
	[DISCHARGE_WARDID] [tinyint] NULL,
	[ACKNOWLEDGE_STATUS] [varchar](255) NOT NULL,
	[CREATETIME] [datetime] NOT NULL,
	[UPDATETIME] [datetime] NOT NULL,
	[ACKNOWLEDGETIME] [datetime] NULL,
	[OUTCOMETIME] [datetime] NOT NULL,
	[FIRSTRESERVATIONTIME] [datetime] NULL,
	[CURRENTRESERVATIONTIME] [datetime] NULL,
 CONSTRAINT [PK_CALLOUT] PRIMARY KEY CLUSTERED 
(
	[ROW_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

DROP TABLE [dbo].[CAREGIVERS]
GO

/****** Object:  Table [dbo].[CAREGIVERS]    Script Date: 4/14/2019 4:54:27 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CAREGIVERS](
	[ROW_ID] [int] NOT NULL,
	[CGID] [smallint] NOT NULL,
	[LABEL] [varchar](255) NULL,
	[DESCRIPTION] [varchar](255) NULL,
 CONSTRAINT [PK_CAREGIVERS] PRIMARY KEY CLUSTERED 
(
	[CGID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


/****** Object:  Table [dbo].[CHARTEVENTS]    Script Date: 4/14/2019 4:54:58 PM ******/
DROP TABLE [dbo].[CHARTEVENTS]
GO

/****** Object:  Table [dbo].[CHARTEVENTS]    Script Date: 4/14/2019 4:54:58 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CHARTEVENTS](
	[ROW_ID] [bigint] NULL,
	[SUBJECT_ID] [bigint] NULL,
	[HADM_ID] [bigint] NULL,
	[ICUSTAY_ID] [bigint] NULL,
	[ITEMID] [bigint] NULL,
	[CHARTTIME] [datetime] NULL,
	[STORETIME] [datetime] NULL,
	[CGID] [nvarchar](max) NULL,
	[VALUE] [nvarchar](max) NULL,
	[VALUENUM] [float] NULL,
	[VALUEUOM] [varchar](max) NULL,
	[WARNING] [bigint] NULL,
	[ERROR] [bigint] NULL,
	[RESULTSTATUS] [nvarchar](max) NULL,
	[STOPPED] [varchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

/****** Object:  Table [dbo].[CPTEVENTS]    Script Date: 4/14/2019 4:55:18 PM ******/
DROP TABLE [dbo].[CPTEVENTS]
GO

/****** Object:  Table [dbo].[CPTEVENTS]    Script Date: 4/14/2019 4:55:18 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CPTEVENTS](
	[ROW_ID] [int] NOT NULL,
	[SUBJECT_ID] [int] NOT NULL,
	[HADM_ID] [int] NOT NULL,
	[COSTCENTER] [varchar](10) NOT NULL,
	[CHARTDATE] [datetime] NULL,
	[CPT_CD] [varchar](10) NOT NULL,
	[CPT_NUMBER] [int] NULL,
	[CPT_SUFFIX] [varchar](5) NULL,
	[TICKET_ID_SEQ] [smallint] NULL,
	[SECTIONHEADER] [varchar](50) NULL,
	[SUBSECTIONHEADER] [varchar](300) NULL,
	[DESCRIPTION] [varchar](255) NULL,
 CONSTRAINT [PK_CPTEVENTS] PRIMARY KEY CLUSTERED 
(
	[ROW_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


/****** Object:  Table [dbo].[D_CPT]    Script Date: 4/14/2019 4:55:33 PM ******/
DROP TABLE [dbo].[D_CPT]
GO

/****** Object:  Table [dbo].[D_CPT]    Script Date: 4/14/2019 4:55:33 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[D_CPT](
	[ROW_ID] [int] NOT NULL,
	[CATEGORY] [tinyint] NOT NULL,
	[SECTIONRANGE] [varchar](100) NOT NULL,
	[SECTIONHEADER] [varchar](50) NOT NULL,
	[SUBSECTIONRANGE] [varchar](100) NOT NULL,
	[SUBSECTIONHEADER] [varchar](300) NOT NULL,
	[CODESUFFIX] [varchar](5) NULL,
	[MINCODEINSUBSECTION] [int] NOT NULL,
	[MAXCODEINSUBSECTION] [int] NOT NULL,
 CONSTRAINT [PK_D_CPT] PRIMARY KEY CLUSTERED 
(
	[ROW_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


/****** Object:  Table [dbo].[D_ICD_DIAGNOSES]    Script Date: 4/14/2019 4:55:56 PM ******/
DROP TABLE [dbo].[D_ICD_DIAGNOSES]
GO

/****** Object:  Table [dbo].[D_ICD_DIAGNOSES]    Script Date: 4/14/2019 4:55:56 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[D_ICD_DIAGNOSES](
	[ROW_ID] [int] NOT NULL,
	[ICD9_CODE] [varchar](10) NOT NULL,
	[SHORT_TITLE] [varchar](50) NOT NULL,
	[LONG_TITLE] [varchar](300) NOT NULL,
 CONSTRAINT [PK_D_ICD_DIAGNOSES] PRIMARY KEY CLUSTERED 
(
	[ICD9_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


/****** Object:  Table [dbo].[D_ICD_PROCEDURES]    Script Date: 4/14/2019 4:56:08 PM ******/
DROP TABLE [dbo].[D_ICD_PROCEDURES]
GO

/****** Object:  Table [dbo].[D_ICD_PROCEDURES]    Script Date: 4/14/2019 4:56:08 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[D_ICD_PROCEDURES](
	[ROW_ID] [int] NOT NULL,
	[ICD9_CODE] [varchar](10) NOT NULL,
	[SHORT_TITLE] [varchar](50) NOT NULL,
	[LONG_TITLE] [varchar](300) NOT NULL,
 CONSTRAINT [PK_D_ICD_PROCEDURES] PRIMARY KEY CLUSTERED 
(
	[ICD9_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


/****** Object:  Table [dbo].[D_ITEMS]    Script Date: 4/14/2019 4:57:08 PM ******/
DROP TABLE [dbo].[D_ITEMS]
GO

/****** Object:  Table [dbo].[D_ITEMS]    Script Date: 4/14/2019 4:57:08 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[D_ITEMS](
	[ROW_ID] [int] NOT NULL,
	[ITEMID] [int] NOT NULL,
	[LABEL] [varchar](255) NULL,
	[ABBREVIATION] [varchar](255) NULL,
	[DBSOURCE] [varchar](255) NOT NULL,
	[LINKSTO] [varchar](255) NULL,
	[CATEGORY] [varchar](255) NULL,
	[UNITNAME] [varchar](255) NULL,
	[PARAM_TYPE] [varchar](255) NULL,
	[CONCEPTID] [varchar](255) NULL,
 CONSTRAINT [PK_D_ITEMS] PRIMARY KEY CLUSTERED 
(
	[ITEMID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


/****** Object:  Table [dbo].[D_LABITEMS]    Script Date: 4/14/2019 4:57:19 PM ******/
DROP TABLE [dbo].[D_LABITEMS]
GO

/****** Object:  Table [dbo].[D_LABITEMS]    Script Date: 4/14/2019 4:57:19 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[D_LABITEMS](
	[ROW_ID] [int] NOT NULL,
	[ITEMID] [int] NOT NULL,
	[LABEL] [varchar](255) NOT NULL,
	[FLUID] [varchar](255) NOT NULL,
	[CATEGORY] [varchar](255) NOT NULL,
	[LOINC_CODE] [varchar](255) NULL,
 CONSTRAINT [PK_D_LABITEMS] PRIMARY KEY CLUSTERED 
(
	[ITEMID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


/****** Object:  Table [dbo].[DATETIMEEVENTS]    Script Date: 4/14/2019 4:57:39 PM ******/
DROP TABLE [dbo].[DATETIMEEVENTS]
GO

/****** Object:  Table [dbo].[DATETIMEEVENTS]    Script Date: 4/14/2019 4:57:39 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DATETIMEEVENTS](
	[ROW_ID] [int] NOT NULL,
	[SUBJECT_ID] [int] NOT NULL,
	[HADM_ID] [int] NULL,
	[ICUSTAY_ID] [int] NULL,
	[ITEMID] [int] NOT NULL,
	[CHARTTIME] [datetime] NOT NULL,
	[STORETIME] [datetime] NOT NULL,
	[CGID] [smallint] NOT NULL,
	[VALUE] [datetime] NULL,
	[VALUEUOM] [varchar](255) NOT NULL,
	[WARNING] [tinyint] NULL,
	[ERROR] [tinyint] NULL,
	[RESULTSTATUS] [varchar](255) NULL,
	[STOPPED] [varchar](255) NULL,
 CONSTRAINT [PK_DATETIMEEVENTS] PRIMARY KEY CLUSTERED 
(
	[ROW_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[DIAGNOSES_ICD]    Script Date: 4/14/2019 4:57:50 PM ******/
DROP TABLE [dbo].[DIAGNOSES_ICD]
GO

/****** Object:  Table [dbo].[DIAGNOSES_ICD]    Script Date: 4/14/2019 4:57:50 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DIAGNOSES_ICD](
	[ROW_ID] [int] NOT NULL,
	[SUBJECT_ID] [int] NOT NULL,
	[HADM_ID] [int] NOT NULL,
	[SEQ_NUM] [tinyint] NULL,
	[ICD9_CODE] [varchar](255) NULL,
 CONSTRAINT [PK_DIAGNOSES_ICD] PRIMARY KEY CLUSTERED 
(
	[ROW_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


/****** Object:  Table [dbo].[DRGCODES]    Script Date: 4/14/2019 4:58:04 PM ******/
DROP TABLE [dbo].[DRGCODES]
GO

/****** Object:  Table [dbo].[DRGCODES]    Script Date: 4/14/2019 4:58:04 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DRGCODES](
	[ROW_ID] [int] NOT NULL,
	[SUBJECT_ID] [int] NOT NULL,
	[HADM_ID] [int] NOT NULL,
	[DRG_TYPE] [varchar](20) NOT NULL,
	[DRG_CODE] [varchar](20) NOT NULL,
	[DESCRIPTION] [varchar](300) NULL,
	[DRG_SEVERITY] [tinyint] NULL,
	[DRG_MORTALITY] [tinyint] NULL,
 CONSTRAINT [PK_DRGCODES] PRIMARY KEY CLUSTERED 
(
	[ROW_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


/****** Object:  Table [dbo].[ICUSTAYS]    Script Date: 4/14/2019 4:58:19 PM ******/
DROP TABLE [dbo].[ICUSTAYS]
GO

/****** Object:  Table [dbo].[ICUSTAYS]    Script Date: 4/14/2019 4:58:19 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ICUSTAYS](
	[ROW_ID] [int] NOT NULL,
	[SUBJECT_ID] [int] NOT NULL,
	[HADM_ID] [int] NOT NULL,
	[ICUSTAY_ID] [int] NOT NULL,
	[DBSOURCE] [varchar](255) NOT NULL,
	[FIRST_CAREUNIT] [varchar](255) NOT NULL,
	[LAST_CAREUNIT] [varchar](255) NOT NULL,
	[FIRST_WARDID] [tinyint] NOT NULL,
	[LAST_WARDID] [tinyint] NOT NULL,
	[INTIME] [datetime] NOT NULL,
	[OUTTIME] [datetime] NULL,
	[LOS] [float] NULL,
 CONSTRAINT [PK_ICUSTAYS] PRIMARY KEY CLUSTERED 
(
	[ICUSTAY_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[INPUTEVENTS_CV]    Script Date: 4/14/2019 4:58:31 PM ******/
DROP TABLE [dbo].[INPUTEVENTS_CV]
GO

/****** Object:  Table [dbo].[INPUTEVENTS_CV]    Script Date: 4/14/2019 4:58:31 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[INPUTEVENTS_CV](
	[ROW_ID] [int] NOT NULL,
	[SUBJECT_ID] [int] NOT NULL,
	[HADM_ID] [int] NULL,
	[ICUSTAY_ID] [int] NULL,
	[CHARTTIME] [datetime] NOT NULL,
	[ITEMID] [int] NOT NULL,
	[AMOUNT] [float] NULL,
	[AMOUNTUOM] [varchar](255) NULL,
	[RATE] [float] NULL,
	[RATEUOM] [varchar](255) NULL,
	[STORETIME] [datetime] NOT NULL,
	[CGID] [smallint] NULL,
	[ORDERID] [int] NOT NULL,
	[LINKORDERID] [int] NOT NULL,
	[STOPPED] [varchar](255) NULL,
	[NEWBOTTLE] [tinyint] NULL,
	[ORIGINALAMOUNT] [float] NULL,
	[ORIGINALAMOUNTUOM] [varchar](255) NULL,
	[ORIGINALROUTE] [varchar](255) NULL,
	[ORIGINALRATE] [float] NULL,
	[ORIGINALRATEUOM] [varchar](255) NULL,
	[ORIGINALSITE] [varchar](255) NULL,
 CONSTRAINT [PK_INPUTEVENTS_CV] PRIMARY KEY CLUSTERED 
(
	[ROW_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[INPUTEVENTS_MV]    Script Date: 4/14/2019 4:58:45 PM ******/
DROP TABLE [dbo].[INPUTEVENTS_MV]
GO

/****** Object:  Table [dbo].[INPUTEVENTS_MV]    Script Date: 4/14/2019 4:58:45 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[INPUTEVENTS_MV](
	[ROW_ID] [int] NOT NULL,
	[SUBJECT_ID] [int] NOT NULL,
	[HADM_ID] [int] NOT NULL,
	[ICUSTAY_ID] [int] NULL,
	[STARTTIME] [datetime] NOT NULL,
	[ENDTIME] [datetime] NOT NULL,
	[ITEMID] [int] NOT NULL,
	[AMOUNT] [float] NOT NULL,
	[AMOUNTUOM] [varchar](255) NOT NULL,
	[RATE] [float] NULL,
	[RATEUOM] [varchar](255) NULL,
	[STORETIME] [datetime] NOT NULL,
	[CGID] [smallint] NOT NULL,
	[ORDERID] [int] NOT NULL,
	[LINKORDERID] [int] NOT NULL,
	[ORDERCATEGORYNAME] [varchar](255) NOT NULL,
	[SECONDARYORDERCATEGORYNAME] [varchar](255) NULL,
	[ORDERCOMPONENTTYPEDESCRIPTION] [varchar](255) NOT NULL,
	[ORDERCATEGORYDESCRIPTION] [varchar](255) NOT NULL,
	[PATIENTWEIGHT] [float] NOT NULL,
	[TOTALAMOUNT] [float] NULL,
	[TOTALAMOUNTUOM] [varchar](255) NULL,
	[ISOPENBAG] [tinyint] NOT NULL,
	[CONTINUEINNEXTDEPT] [tinyint] NOT NULL,
	[CANCELREASON] [tinyint] NOT NULL,
	[STATUSDESCRIPTION] [varchar](255) NOT NULL,
	[COMMENTS_EDITEDBY] [varchar](255) NULL,
	[COMMENTS_CANCELEDBY] [varchar](255) NULL,
	[COMMENTS_DATE] [datetime] NULL,
	[ORIGINALAMOUNT] [float] NOT NULL,
	[ORIGINALRATE] [float] NOT NULL,
 CONSTRAINT [PK_INPUTEVENTS_MV] PRIMARY KEY CLUSTERED 
(
	[ROW_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


/****** Object:  Table [dbo].[LABEVENTS]    Script Date: 4/14/2019 4:58:57 PM ******/
DROP TABLE [dbo].[LABEVENTS]
GO

/****** Object:  Table [dbo].[LABEVENTS]    Script Date: 4/14/2019 4:58:57 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LABEVENTS](
	[ROW_ID] [int] NOT NULL,
	[SUBJECT_ID] [int] NOT NULL,
	[HADM_ID] [int] NULL,
	[ITEMID] [int] NOT NULL,
	[CHARTTIME] [datetime] NOT NULL,
	[VALUE] [varchar](255) NULL,
	[VALUENUM] [float] NULL,
	[VALUEUOM] [varchar](255) NULL,
	[FLAG] [varchar](255) NULL,
 CONSTRAINT [PK_LABEVENTS] PRIMARY KEY CLUSTERED 
(
	[ROW_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


/****** Object:  Table [dbo].[MICROBIOLOGYEVENTS]    Script Date: 4/14/2019 4:59:16 PM ******/
DROP TABLE [dbo].[MICROBIOLOGYEVENTS]
GO

/****** Object:  Table [dbo].[MICROBIOLOGYEVENTS]    Script Date: 4/14/2019 4:59:16 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MICROBIOLOGYEVENTS](
	[ROW_ID] [int] NOT NULL,
	[SUBJECT_ID] [int] NOT NULL,
	[HADM_ID] [int] NULL,
	[CHARTDATE] [datetime] NOT NULL,
	[CHARTTIME] [datetime] NULL,
	[SPEC_ITEMID] [int] NULL,
	[SPEC_TYPE_DESC] [varchar](255) NOT NULL,
	[ORG_ITEMID] [int] NULL,
	[ORG_NAME] [varchar](255) NULL,
	[ISOLATE_NUM] [tinyint] NULL,
	[AB_ITEMID] [int] NULL,
	[AB_NAME] [varchar](255) NULL,
	[DILUTION_TEXT] [varchar](255) NULL,
	[DILUTION_COMPARISON] [varchar](255) NULL,
	[DILUTION_VALUE] [smallint] NULL,
	[INTERPRETATION] [varchar](255) NULL,
 CONSTRAINT [PK_MICROBIOLOGYEVENTS] PRIMARY KEY CLUSTERED 
(
	[ROW_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


/****** Object:  Table [dbo].[OUTPUTEVENTS]    Script Date: 4/14/2019 4:59:29 PM ******/
DROP TABLE [dbo].[OUTPUTEVENTS]
GO

/****** Object:  Table [dbo].[OUTPUTEVENTS]    Script Date: 4/14/2019 4:59:29 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[OUTPUTEVENTS](
	[ROW_ID] [int] NOT NULL,
	[SUBJECT_ID] [int] NOT NULL,
	[HADM_ID] [int] NULL,
	[ICUSTAY_ID] [int] NULL,
	[CHARTTIME] [datetime] NOT NULL,
	[ITEMID] [int] NOT NULL,
	[VALUE] [float] NULL,
	[VALUEUOM] [varchar](255) NULL,
	[STORETIME] [datetime] NOT NULL,
	[CGID] [smallint] NOT NULL,
	[STOPPED] [varchar](255) NULL,
	[NEWBOTTLE] [varchar](255) NULL,
	[ISERROR] [varchar](255) NULL,
 CONSTRAINT [PK_OUTPUTEVENTS] PRIMARY KEY CLUSTERED 
(
	[ROW_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


/****** Object:  Table [dbo].[PATIENTS]    Script Date: 4/14/2019 4:59:37 PM ******/
DROP TABLE [dbo].[PATIENTS]
GO

/****** Object:  Table [dbo].[PATIENTS]    Script Date: 4/14/2019 4:59:37 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PATIENTS](
	[ROW_ID] [int] NOT NULL,
	[SUBJECT_ID] [int] NOT NULL,
	[GENDER] [varchar](255) NOT NULL,
	[DOB] [datetime] NULL,
	[DOD] [datetime] NULL,
	[DOD_HOSP] [datetime] NULL,
	[DOD_SSN] [datetime] NULL,
	[EXPIRE_FLAG] [tinyint] NOT NULL,
 CONSTRAINT [PK_PATIENTS] PRIMARY KEY CLUSTERED 
(
	[SUBJECT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


/****** Object:  Table [dbo].[PRESCRIPTIONS]    Script Date: 4/14/2019 4:59:58 PM ******/
DROP TABLE [dbo].[PRESCRIPTIONS]
GO

/****** Object:  Table [dbo].[PRESCRIPTIONS]    Script Date: 4/14/2019 4:59:58 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PRESCRIPTIONS](
	[ROW_ID] [int] NOT NULL,
	[SUBJECT_ID] [int] NOT NULL,
	[HADM_ID] [int] NOT NULL,
	[ICUSTAY_ID] [int] NULL,
	[STARTDATE] [datetime] NULL,
	[ENDDATE] [datetime] NULL,
	[DRUG_TYPE] [varchar](255) NOT NULL,
	[DRUG] [varchar](255) NULL,
	[DRUG_NAME_POE] [varchar](255) NULL,
	[DRUG_NAME_GENERIC] [varchar](255) NULL,
	[FORMULARY_DRUG_CD] [varchar](255) NULL,
	[GSN] [varchar](200) NULL,
	[NDC] [varchar](255) NULL,
	[PROD_STRENGTH] [varchar](255) NULL,
	[DOSE_VAL_RX] [varchar](255) NULL,
	[DOSE_UNIT_RX] [varchar](255) NULL,
	[FORM_VAL_DISP] [varchar](255) NULL,
	[FORM_UNIT_DISP] [varchar](255) NULL,
	[ROUTE] [varchar](255) NULL,
 CONSTRAINT [PK_PRESCRIPTIONS] PRIMARY KEY CLUSTERED 
(
	[ROW_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


/****** Object:  Table [dbo].[PROCEDUREEVENTS_MV]    Script Date: 4/14/2019 5:00:10 PM ******/
DROP TABLE [dbo].[PROCEDUREEVENTS_MV]
GO

/****** Object:  Table [dbo].[PROCEDUREEVENTS_MV]    Script Date: 4/14/2019 5:00:10 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PROCEDUREEVENTS_MV](
	[ROW_ID] [int] NOT NULL,
	[SUBJECT_ID] [int] NOT NULL,
	[HADM_ID] [int] NOT NULL,
	[ICUSTAY_ID] [int] NULL,
	[STARTTIME] [datetime] NOT NULL,
	[ENDTIME] [datetime] NOT NULL,
	[ITEMID] [int] NOT NULL,
	[VALUE] [float] NOT NULL,
	[VALUEUOM] [varchar](255) NOT NULL,
	[LOCATION] [varchar](255) NULL,
	[LOCATIONCATEGORY] [varchar](255) NULL,
	[STORETIME] [datetime] NOT NULL,
	[CGID] [smallint] NOT NULL,
	[ORDERID] [int] NOT NULL,
	[LINKORDERID] [int] NOT NULL,
	[ORDERCATEGORYNAME] [varchar](255) NOT NULL,
	[SECONDARYORDERCATEGORYNAME] [varchar](255) NULL,
	[ORDERCATEGORYDESCRIPTION] [varchar](255) NOT NULL,
	[ISOPENBAG] [tinyint] NOT NULL,
	[CONTINUEINNEXTDEPT] [tinyint] NOT NULL,
	[CANCELREASON] [tinyint] NOT NULL,
	[STATUSDESCRIPTION] [varchar](255) NOT NULL,
	[COMMENTS_EDITEDBY] [varchar](255) NULL,
	[COMMENTS_CANCELEDBY] [varchar](255) NULL,
	[COMMENTS_DATE] [datetime] NULL,
 CONSTRAINT [PK_PROCEDUREEVENTS_MV] PRIMARY KEY CLUSTERED 
(
	[ORDERID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


/****** Object:  Table [dbo].[PROCEDURES_ICD]    Script Date: 4/14/2019 5:00:20 PM ******/
DROP TABLE [dbo].[PROCEDURES_ICD]
GO

/****** Object:  Table [dbo].[PROCEDURES_ICD]    Script Date: 4/14/2019 5:00:20 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PROCEDURES_ICD](
	[ROW_ID] [int] NOT NULL,
	[SUBJECT_ID] [int] NOT NULL,
	[HADM_ID] [int] NOT NULL,
	[SEQ_NUM] [tinyint] NOT NULL,
	[ICD9_CODE] [varchar](255) NOT NULL,
 CONSTRAINT [PK_PROCEDURES_ICD] PRIMARY KEY CLUSTERED 
(
	[ROW_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


/****** Object:  Table [dbo].[ref_HCC_Desciptions]    Script Date: 4/14/2019 5:00:37 PM ******/
DROP TABLE [dbo].[ref_HCC_Desciptions]
GO

/****** Object:  Table [dbo].[ref_HCC_Desciptions]    Script Date: 4/14/2019 5:00:37 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ref_HCC_Desciptions](
	[HCC_Code] [int] NOT NULL,
	[HCC_Description] [nvarchar](255) NOT NULL,
 CONSTRAINT [PK_ref_ICD9_to_HCC_Mappings] PRIMARY KEY CLUSTERED 
(
	[HCC_Code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


/****** Object:  Table [dbo].[ref_ICD9_to_HCC_Mapping]    Script Date: 4/14/2019 5:00:46 PM ******/
DROP TABLE [dbo].[ref_ICD9_to_HCC_Mapping]
GO

/****** Object:  Table [dbo].[ref_ICD9_to_HCC_Mapping]    Script Date: 4/14/2019 5:00:46 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ref_ICD9_to_HCC_Mapping](
	[ICD9_Code] [nvarchar](50) NOT NULL,
	[HCC_Code] [int] NOT NULL,
 CONSTRAINT [PK_ref_ICD9_to_HCC_Mapping] PRIMARY KEY CLUSTERED 
(
	[ICD9_Code] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


/****** Object:  Table [dbo].[SERVICES]    Script Date: 4/14/2019 5:00:58 PM ******/
DROP TABLE [dbo].[SERVICES]
GO

/****** Object:  Table [dbo].[SERVICES]    Script Date: 4/14/2019 5:00:58 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SERVICES](
	[ROW_ID] [int] NOT NULL,
	[SUBJECT_ID] [int] NOT NULL,
	[HADM_ID] [int] NOT NULL,
	[TRANSFERTIME] [datetime] NOT NULL,
	[PREV_SERVICE] [varchar](255) NULL,
	[CURR_SERVICE] [varchar](255) NOT NULL,
 CONSTRAINT [PK_SERVICES] PRIMARY KEY CLUSTERED 
(
	[ROW_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


/****** Object:  Table [dbo].[TRANSFERS]    Script Date: 4/14/2019 5:01:16 PM ******/
DROP TABLE [dbo].[TRANSFERS]
GO

/****** Object:  Table [dbo].[TRANSFERS]    Script Date: 4/14/2019 5:01:16 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TRANSFERS](
	[ROW_ID] [int] NOT NULL,
	[SUBJECT_ID] [int] NOT NULL,
	[HADM_ID] [int] NOT NULL,
	[ICUSTAY_ID] [int] NULL,
	[DBSOURCE] [varchar](255) NULL,
	[EVENTTYPE] [varchar](255) NULL,
	[PREV_CAREUNIT] [varchar](255) NULL,
	[CURR_CAREUNIT] [varchar](255) NULL,
	[PREV_WARDID] [tinyint] NULL,
	[CURR_WARDID] [tinyint] NULL,
	[INTIME] [datetime] NULL,
	[OUTTIME] [datetime] NULL,
	[LOS] [float] NULL,
 CONSTRAINT [PK_TRANSFERS] PRIMARY KEY CLUSTERED 
(
	[ROW_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO




